### ISSUE TITLE
Popup not displaying, Firefox 56

### ISSUE THREAD

**Issue by aeltee** [meetDeveloper/Dictionary-Anywhere#19]
On my Firefox 56 install, dictionary anywhere does not show the definition pop up when double clicking words. I have set the dom.webcomponents.shadowdom.enabled boolean to true. I can however see that in the extension options, the number in the word history is increasing with the words I am trying to show the definition pop up for. Is there any other setting for Firefox 56 that might be preventing the pop up? I have tried disabling adblock and other extensions but still nothing displays.
Thank you.

**Comment by meetDeveloper** [comment]
The add-on supports Firefox version 57 and above, is there any reason that
you are still on version 56?

**Comment by meetDeveloper** [comment]
I think Shadow Dom is not fully supported in Firefox 56.

**Comment by meetDeveloper** [comment]
Can you check console when you double click any word, it might show some
error that we can use to find the problem

**Comment by aeltee** [comment]
Here are a few of the console results upon double clicking 3 different words:
TypeError: hostDiv.attachShadow is not a function[Learn More]  dictionary.js:66:9
All candidate resources failed to load. Media load paused.  _generated_background_page.html
TypeError: createdDiv is undefined[Learn More]  dictionary.js:151:13
ReferenceError: AbortController is not defined[Learn More]  github-bootstrap-c8d23990.js:1:34025
TypeError: hostDiv.attachShadow is not a function[Learn More]  dictionary.js:66:9
All candidate resources failed to load. Media load paused.  _generated_background_page.html
TypeError: createdDiv is undefined[Learn More]  dictionary.js:151:13
Attempt to set a forbidden header was denied: Connection  1986475897-lcs_client_bin.js:123:386
ReferenceError: AbortController is not defined[Learn More]  github-bootstrap-c8d23990.js:1:34025
TypeError: hostDiv.attachShadow is not a function[Learn More]  dictionary.js:66:9
All candidate resources failed to load. Media load paused.  _generated_background_page.html
TypeError: createdDiv is undefined[Learn More]  dictionary.js:151:13

I agree I that I think shadow dom functioning is not available in Firefox 56, regardless of about:config setting. I remember a different extension was not displaying something properly and it was because of shadow dom. On the Firefox Extensions site, the latest version of dictionary anywhere states 'Works with firefox 48.0 and later', which is why I tried it. I have stuck with Firefox version 56 because with Firefox 57 came the switch to quantum and webextension, and many extensions that are important to me thus no longer worked nor do they have satisfactory webextension alternatives to switch to.

Thanks for the help. I tried your extension in my up to date Firefox dev version 79.0b7 and it works well, better than the other dictionary/translation extension I was comparing it to as it managed to find a definition much more consistently, and also especially the auto saved history of looked up words, which was the main reason I gave your extension a try. Greater number of language options (chinese, etc) would be the one thing the other translation was better for. But I don't really use that up to date Firefox because despite my attempts, I could not get all the extension functionality I was so used to in 56.

**Comment by meetDeveloper** [comment]
Can you tell me where is `Works with Firefox 48.0 and late` written? What all extensions do you have that you are not able to get in new Firefox, I could find those for you or if I get time will build those extension.

I am planning to add host of languages soon, I have my dictionary API hosted at dictionaryapi.dev. I am currently making it more stable and then use that to find meaning for any words in 20 or so languages.

**Comment by meetDeveloper** [comment]
@aeltee

**Comment by aeltee** [comment]
Can you tell me where is Works with Firefox 48.0 and late written?- https://addons.mozilla.org/en-US/firefox/addon/dictionary-anyvhere/versions/?src=featured

Extensions from Firefox 56 that I can't live without nor could I find satisfactory quantum alternatives:

Thumbnail Zoom Plus is one that I sorely missed in Firefox 79 as I just got so used to it. On mouse over most images/thumbnails auto pops up a max enlarged to screen size image and it auto closes the pop up when no longer hovering over the original image. Image Max URL nearly did the trick, but I just couldn't configure it to work as smoothly (it was popping up when I didn't want, pop ups took a few seconds instead of instantly showing, popup didn't close when no longer hovering consistently)

Tab Mix Plus is probably one of the most commonly requested extensions to be updated for quantum, and none has been able to have so so many features. Also the undo close tab button that when clicked shows a list of recently closed tabs to reopen.

Menu Wizard. I think there are ways to customize add/remove things from all the various context menus but its through editing css files and not by an easy GUI.

Context Search X (select text, right click for context menu and on the first menu opened customizable search engines to search with. Some alternatives basically do this, but not via context menu without clicking to a submenu)

Bookmark Favicon Changer (custom bookmark favicons that can be easily changed via context menu or extension options GUI)

Roomy Bookmarks Toolbar (bookmarks bar with these customized favicons without text so just a row of small icons)

Mouseover Bookmarks Toolbar (folders on the bookmark bar are opened by mouse over)

Another function I find super annoying is the lack of being able to set a custom website as your default new tab/home page, but when making a new tab, you should auto have the location bar selected and be able to type things (search, URL) without your typing getting overwritten by the URL of the loading home tab.

Those are the things I can think of. Some of them I found really hard to live without after getting everything super efficient and super customized in Firefox 56. Some of these functions are easy to make but others are probably complicated to develop. But those are just some ideas for extensions functions that I couldn't replicate easily in the updated Firefox.

**Comment by meetDeveloper** [comment]
@aeltee I looked why it is showing that, I will fix that and if got time will work on the other addons that you suggested that are not available in current firefox versions. I am extremely sorry that you are not able to use the extension due to this. I will in next weekend modify the code a little and provide you the extension that works with your browser version.
